//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ValidationSoap")]
    public interface ValidationSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.isEmailResponse> isEmailAsync(ServiceReference1.isEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isFrancePhoneNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.isFrancePhoneNumberResponse> isFrancePhoneNumberAsync(ServiceReference1.isFrancePhoneNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isGermanPhoneNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.isGermanPhoneNumberResponse> isGermanPhoneNumberAsync(ServiceReference1.isGermanPhoneNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isUSPhoneNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.isUSPhoneNumberResponse> isUSPhoneNumberAsync(ServiceReference1.isUSPhoneNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isIp", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.isIpResponse> isIpAsync(ServiceReference1.isIpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isISBN", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.isISBNResponse> isISBNAsync(ServiceReference1.isISBNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isGUID", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.isGUIDResponse> isGUIDAsync(ServiceReference1.isGUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isURL", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.isURLResponse> isURLAsync(ServiceReference1.isURLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/is5Numbers", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.is5NumbersResponse> is5NumbersAsync(ServiceReference1.is5NumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isEmail", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isEmailRequestBody Body;
        
        public isEmailRequest()
        {
        }
        
        public isEmailRequest(ServiceReference1.isEmailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isEmailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isEmailRequestBody()
        {
        }
        
        public isEmailRequestBody(string str)
        {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isEmailResponseBody Body;
        
        public isEmailResponse()
        {
        }
        
        public isEmailResponse(ServiceReference1.isEmailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isEmailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isEmailResult;
        
        public isEmailResponseBody()
        {
        }
        
        public isEmailResponseBody(bool isEmailResult)
        {
            this.isEmailResult = isEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isFrancePhoneNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isFrancePhoneNumber", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isFrancePhoneNumberRequestBody Body;
        
        public isFrancePhoneNumberRequest()
        {
        }
        
        public isFrancePhoneNumberRequest(ServiceReference1.isFrancePhoneNumberRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isFrancePhoneNumberRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isFrancePhoneNumberRequestBody()
        {
        }
        
        public isFrancePhoneNumberRequestBody(string str)
        {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isFrancePhoneNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isFrancePhoneNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isFrancePhoneNumberResponseBody Body;
        
        public isFrancePhoneNumberResponse()
        {
        }
        
        public isFrancePhoneNumberResponse(ServiceReference1.isFrancePhoneNumberResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isFrancePhoneNumberResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isFrancePhoneNumberResult;
        
        public isFrancePhoneNumberResponseBody()
        {
        }
        
        public isFrancePhoneNumberResponseBody(bool isFrancePhoneNumberResult)
        {
            this.isFrancePhoneNumberResult = isFrancePhoneNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isGermanPhoneNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isGermanPhoneNumber", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isGermanPhoneNumberRequestBody Body;
        
        public isGermanPhoneNumberRequest()
        {
        }
        
        public isGermanPhoneNumberRequest(ServiceReference1.isGermanPhoneNumberRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isGermanPhoneNumberRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isGermanPhoneNumberRequestBody()
        {
        }
        
        public isGermanPhoneNumberRequestBody(string str)
        {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isGermanPhoneNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isGermanPhoneNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isGermanPhoneNumberResponseBody Body;
        
        public isGermanPhoneNumberResponse()
        {
        }
        
        public isGermanPhoneNumberResponse(ServiceReference1.isGermanPhoneNumberResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isGermanPhoneNumberResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isGermanPhoneNumberResult;
        
        public isGermanPhoneNumberResponseBody()
        {
        }
        
        public isGermanPhoneNumberResponseBody(bool isGermanPhoneNumberResult)
        {
            this.isGermanPhoneNumberResult = isGermanPhoneNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isUSPhoneNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isUSPhoneNumber", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isUSPhoneNumberRequestBody Body;
        
        public isUSPhoneNumberRequest()
        {
        }
        
        public isUSPhoneNumberRequest(ServiceReference1.isUSPhoneNumberRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isUSPhoneNumberRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isUSPhoneNumberRequestBody()
        {
        }
        
        public isUSPhoneNumberRequestBody(string str)
        {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isUSPhoneNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isUSPhoneNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isUSPhoneNumberResponseBody Body;
        
        public isUSPhoneNumberResponse()
        {
        }
        
        public isUSPhoneNumberResponse(ServiceReference1.isUSPhoneNumberResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isUSPhoneNumberResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isUSPhoneNumberResult;
        
        public isUSPhoneNumberResponseBody()
        {
        }
        
        public isUSPhoneNumberResponseBody(bool isUSPhoneNumberResult)
        {
            this.isUSPhoneNumberResult = isUSPhoneNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isIpRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isIp", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isIpRequestBody Body;
        
        public isIpRequest()
        {
        }
        
        public isIpRequest(ServiceReference1.isIpRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isIpRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isIpRequestBody()
        {
        }
        
        public isIpRequestBody(string str)
        {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isIpResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isIpResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isIpResponseBody Body;
        
        public isIpResponse()
        {
        }
        
        public isIpResponse(ServiceReference1.isIpResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isIpResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isIpResult;
        
        public isIpResponseBody()
        {
        }
        
        public isIpResponseBody(bool isIpResult)
        {
            this.isIpResult = isIpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isISBNRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isISBN", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isISBNRequestBody Body;
        
        public isISBNRequest()
        {
        }
        
        public isISBNRequest(ServiceReference1.isISBNRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isISBNRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isISBNRequestBody()
        {
        }
        
        public isISBNRequestBody(string str)
        {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isISBNResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isISBNResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isISBNResponseBody Body;
        
        public isISBNResponse()
        {
        }
        
        public isISBNResponse(ServiceReference1.isISBNResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isISBNResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isISBNResult;
        
        public isISBNResponseBody()
        {
        }
        
        public isISBNResponseBody(bool isISBNResult)
        {
            this.isISBNResult = isISBNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isGUIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isGUID", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isGUIDRequestBody Body;
        
        public isGUIDRequest()
        {
        }
        
        public isGUIDRequest(ServiceReference1.isGUIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isGUIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isGUIDRequestBody()
        {
        }
        
        public isGUIDRequestBody(string str)
        {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isGUIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isGUIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isGUIDResponseBody Body;
        
        public isGUIDResponse()
        {
        }
        
        public isGUIDResponse(ServiceReference1.isGUIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isGUIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isGUIDResult;
        
        public isGUIDResponseBody()
        {
        }
        
        public isGUIDResponseBody(bool isGUIDResult)
        {
            this.isGUIDResult = isGUIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isURLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isURL", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isURLRequestBody Body;
        
        public isURLRequest()
        {
        }
        
        public isURLRequest(ServiceReference1.isURLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isURLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isURLRequestBody()
        {
        }
        
        public isURLRequestBody(string str)
        {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isURLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isURLResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.isURLResponseBody Body;
        
        public isURLResponse()
        {
        }
        
        public isURLResponse(ServiceReference1.isURLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isURLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isURLResult;
        
        public isURLResponseBody()
        {
        }
        
        public isURLResponseBody(bool isURLResult)
        {
            this.isURLResult = isURLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class is5NumbersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="is5Numbers", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.is5NumbersRequestBody Body;
        
        public is5NumbersRequest()
        {
        }
        
        public is5NumbersRequest(ServiceReference1.is5NumbersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class is5NumbersRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public is5NumbersRequestBody()
        {
        }
        
        public is5NumbersRequestBody(string str)
        {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class is5NumbersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="is5NumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.is5NumbersResponseBody Body;
        
        public is5NumbersResponse()
        {
        }
        
        public is5NumbersResponse(ServiceReference1.is5NumbersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class is5NumbersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool is5NumbersResult;
        
        public is5NumbersResponseBody()
        {
        }
        
        public is5NumbersResponseBody(bool is5NumbersResult)
        {
            this.is5NumbersResult = is5NumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ValidationSoapChannel : ServiceReference1.ValidationSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ValidationSoapClient : System.ServiceModel.ClientBase<ServiceReference1.ValidationSoap>, ServiceReference1.ValidationSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ValidationSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ValidationSoapClient.GetBindingForEndpoint(endpointConfiguration), ValidationSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidationSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ValidationSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidationSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ValidationSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.isEmailResponse> ServiceReference1.ValidationSoap.isEmailAsync(ServiceReference1.isEmailRequest request)
        {
            return base.Channel.isEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.isEmailResponse> isEmailAsync(string str)
        {
            ServiceReference1.isEmailRequest inValue = new ServiceReference1.isEmailRequest();
            inValue.Body = new ServiceReference1.isEmailRequestBody();
            inValue.Body.str = str;
            return ((ServiceReference1.ValidationSoap)(this)).isEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.isFrancePhoneNumberResponse> ServiceReference1.ValidationSoap.isFrancePhoneNumberAsync(ServiceReference1.isFrancePhoneNumberRequest request)
        {
            return base.Channel.isFrancePhoneNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.isFrancePhoneNumberResponse> isFrancePhoneNumberAsync(string str)
        {
            ServiceReference1.isFrancePhoneNumberRequest inValue = new ServiceReference1.isFrancePhoneNumberRequest();
            inValue.Body = new ServiceReference1.isFrancePhoneNumberRequestBody();
            inValue.Body.str = str;
            return ((ServiceReference1.ValidationSoap)(this)).isFrancePhoneNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.isGermanPhoneNumberResponse> ServiceReference1.ValidationSoap.isGermanPhoneNumberAsync(ServiceReference1.isGermanPhoneNumberRequest request)
        {
            return base.Channel.isGermanPhoneNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.isGermanPhoneNumberResponse> isGermanPhoneNumberAsync(string str)
        {
            ServiceReference1.isGermanPhoneNumberRequest inValue = new ServiceReference1.isGermanPhoneNumberRequest();
            inValue.Body = new ServiceReference1.isGermanPhoneNumberRequestBody();
            inValue.Body.str = str;
            return ((ServiceReference1.ValidationSoap)(this)).isGermanPhoneNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.isUSPhoneNumberResponse> ServiceReference1.ValidationSoap.isUSPhoneNumberAsync(ServiceReference1.isUSPhoneNumberRequest request)
        {
            return base.Channel.isUSPhoneNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.isUSPhoneNumberResponse> isUSPhoneNumberAsync(string str)
        {
            ServiceReference1.isUSPhoneNumberRequest inValue = new ServiceReference1.isUSPhoneNumberRequest();
            inValue.Body = new ServiceReference1.isUSPhoneNumberRequestBody();
            inValue.Body.str = str;
            return ((ServiceReference1.ValidationSoap)(this)).isUSPhoneNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.isIpResponse> ServiceReference1.ValidationSoap.isIpAsync(ServiceReference1.isIpRequest request)
        {
            return base.Channel.isIpAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.isIpResponse> isIpAsync(string str)
        {
            ServiceReference1.isIpRequest inValue = new ServiceReference1.isIpRequest();
            inValue.Body = new ServiceReference1.isIpRequestBody();
            inValue.Body.str = str;
            return ((ServiceReference1.ValidationSoap)(this)).isIpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.isISBNResponse> ServiceReference1.ValidationSoap.isISBNAsync(ServiceReference1.isISBNRequest request)
        {
            return base.Channel.isISBNAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.isISBNResponse> isISBNAsync(string str)
        {
            ServiceReference1.isISBNRequest inValue = new ServiceReference1.isISBNRequest();
            inValue.Body = new ServiceReference1.isISBNRequestBody();
            inValue.Body.str = str;
            return ((ServiceReference1.ValidationSoap)(this)).isISBNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.isGUIDResponse> ServiceReference1.ValidationSoap.isGUIDAsync(ServiceReference1.isGUIDRequest request)
        {
            return base.Channel.isGUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.isGUIDResponse> isGUIDAsync(string str)
        {
            ServiceReference1.isGUIDRequest inValue = new ServiceReference1.isGUIDRequest();
            inValue.Body = new ServiceReference1.isGUIDRequestBody();
            inValue.Body.str = str;
            return ((ServiceReference1.ValidationSoap)(this)).isGUIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.isURLResponse> ServiceReference1.ValidationSoap.isURLAsync(ServiceReference1.isURLRequest request)
        {
            return base.Channel.isURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.isURLResponse> isURLAsync(string str)
        {
            ServiceReference1.isURLRequest inValue = new ServiceReference1.isURLRequest();
            inValue.Body = new ServiceReference1.isURLRequestBody();
            inValue.Body.str = str;
            return ((ServiceReference1.ValidationSoap)(this)).isURLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.is5NumbersResponse> ServiceReference1.ValidationSoap.is5NumbersAsync(ServiceReference1.is5NumbersRequest request)
        {
            return base.Channel.is5NumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.is5NumbersResponse> is5NumbersAsync(string str)
        {
            ServiceReference1.is5NumbersRequest inValue = new ServiceReference1.is5NumbersRequest();
            inValue.Body = new ServiceReference1.is5NumbersRequestBody();
            inValue.Body.str = str;
            return ((ServiceReference1.ValidationSoap)(this)).is5NumbersAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ValidationSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ValidationSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ValidationSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://renad.org/WebServices/Services/Validation.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ValidationSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://renad.org/WebServices/Services/Validation.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ValidationSoap,
            
            ValidationSoap12,
        }
    }
}
